### ISSUE TITLE
Update 1.5.4 - 1.6.0 HTTP Error 500

### ISSUE THREAD

**Issue by je-we** [IMC-GER/phpBB-External-Links#1]
phpBB3 version: 3.3.13
PHP Version 8.3.8-nmm1

When I try to update the version to 1.6.0 the board page is not loading in Firefox and showing HTTP 500 error in Edge.
ACP is working and when I disable this extension, everything works fine again.

I had followed the usual guidance (disable ext., delete ext. folder, and uploaded the new ext. folder).

Any hint to get a working 1.6.0 extension enabled?

**Comment by IMC-GER** [comment]
Your PHP version is correct and following the update instructions is also correct and important.

Please Purge the cache in ACP on the GENERAL setting site. . 

If the extension does not work afterwards, I need the content of PHP errorlog to narrow down the error.
You can also test whether External Links works when all other extensions are deactivated.

**Comment by je-we** [comment]
Thanks for feedback! Cache was purged a couple of times. I see the problem even if I disable all other extensions and only keep "external-links".

Do you have a documentation ready to hand how to create PHP errorlog? (all-inkl.com server, if this is important). Otherwise I will google it the next days.
Thanks!

**Comment by IMC-GER** [comment]
I find this instruction in the German phpBB support forum.
https://www.phpbb.de/community/viewtopic.php?p=1413561#p1413561

**Comment by je-we** [comment]
OK, Thanks! I have enabled and will watch out, if a file will be created next days. 
It was not created with testing with enabled extension (and the "white" resp. 500 error page).

**Comment by je-we** [comment]
Unfortunately, the log file stays empty and I cannot provide more details. 
I think I will switch back to 1.5.4 in few days as I like and want to have this ext. in my board.

**Comment by IMC-GER** [comment]
I have found another instruction to creating an errorlog at all-inkl.com. I hope you can translate it.
https://all-inkl.com/wichtig/anleitungen/skripte/sonstiges/php-errorlog/anlegen_616.html

I would be interested to know why the extension is not working for you. You could also check whether all files have been uploaded to the server.

**Comment by je-we** [comment]
Kein Problem mit deutscher Anleitung ;-)

I had tried, but as I cannot keep my board "offline" ... stupid question, how can I force a clear php error (independent from your extension)  that I can be sure the log file is used? Enabling extension and the "white" board page => no entry / no log file written.

**Comment by IMC-GER** [comment]
Create a file with this content. Example name: `error.php`. 
`<?php echo 'this line generate an error' `

Copy it to the server and run it.
`https://yourdomain.com/error.php`

It generate an error like this:
`[11-Oct-2024 20:03:33 MET] PHP Parse error:  syntax error, unexpected end of file, expecting "," or ";" in /.../error.php on line 2`

**Comment by je-we** [comment]
OK, found it incl. error log with enabled "external links" extension ;)
This is the log with all extensions. I can try later with your extension enabled only.

`[11-Oct-2024 18:50:45 Europe/Berlin] PHP Fatal error:  Uncaught phpbb\language\exception\language_file_not_found: Language file ./ext/paybas/recenttopics/language/en/recenttopics.php couldn't be opened. in /www/<dummyaddress>/phpbb/language/language_file_loader.php:186`
`Stack trace:`
`#0 /www/<dummyaddress>/phpbb/language/language_file_loader.php(143): phpbb\language\language_file_loader->get_language_file_path('./ext/paybas/re...', 'recenttopics.ph...', Array)`
`#1 /www/<dummyaddress>/phpbb/language/language_file_loader.php(103): phpbb\language\language_file_loader->load_file('./ext/paybas/re...', 'recenttopics', Array, Array)`
`#2 /www/<dummyaddress>/phpbb/language/language.php(643): phpbb\language\language_file_loader->load_extension('paybas/recentto...', 'recenttopics', Array, Array)`
`#3 /www/<dummyaddress>/phpbb/language/language.php(180): phpbb\language\language->load_extension('paybas/recentto...', 'recenttopics')`
`#4 /www/<dummyaddress>/ext/imcger/externallinks/event/main_listener.php(122): phpbb\language\language->add_lang('recenttopics', 'paybas/recentto...')`
`#5 /www/<dummyaddress>/vendor/symfony/event-dispatcher/EventDispatcher.php(214): imcger\externallinks\event\main_listener->set_template_vars(Object(phpbb\event\data), 'core.page_heade...', Object(phpbb\event\dispatcher))`
`#6 /www/<dummyaddress>/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'core.page_heade...', Object(phpbb\event\data))`
`#7 /www/<dummyaddress>/phpbb/event/dispatcher.php(62): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('core.page_heade...', Object(phpbb\event\data))`
`#8 /www/<dummyaddress>/phpbb/event/dispatcher.php(46): phpbb\event\dispatcher->dispatch('core.page_heade...', Object(phpbb\event\data))`
`#9 /www/<dummyaddress>/includes/functions.php(3810): phpbb\event\dispatcher->trigger_event('core.page_heade...', Array)`
`#10 /www/<dummyaddress>/viewtopic.php(2419): page_header('Kaderplanung 20...', true, 7)`
`#11 {main}`
`  thrown in /www/<dummyaddress>/phpbb/language/language_file_loader.php on line 186`
`[11-Oct-2024 20:21:30 Europe/Berlin] PHP Parse error:  syntax error, unexpected end of file, expecting "," or ";" in /www/<dummyaddress>/error.php on line 1`

**Comment by IMC-GER** [comment]
I have found my mistake. A copy & paste mistake. :-( 
I will release the new version by tomorrow.

Thank you for reporting the error.

**Comment by IMC-GER** [comment]
v1.6.1 is online.
Thank you for helping to make external links better.
